### ISSUE TITLE
Upload exploded archive

### ISSUE THREAD

**Issue by jgeorgeson** [JFrogDev/artifactory-cli-go#13]
It'd be great to use this tool to upload a zip to be exploded in a sub-path of a repo, rather than using Curl or using the UI Deploy to a dummy repo then moving the content to the real location.

**Comment by eyalbe4** [comment]
Thanks for this @jgeorgeson. We would like add this enhancement to one of the future versions of the [JFrog CLI](https://github.com/JFrogDev/jfrog-cli-go). 
[JFrog CLI](https://github.com/JFrogDev/jfrog-cli-go) is an evolution of the Artifactory CLI and we threfore recommend migrating to JFrog CLI if you hadn't done so already.

**Comment by jgeorgeson** [comment]
I will submit this to jfrog-cli
