### ISSUE TITLE
Unable to download artfiact from remote repository

### ISSUE THREAD

**Issue by asaddamhussain** [JFrogDev/artifactory-cli-go#17]
Hi,

I am trying to download artifacts from remote repository. Execution completes without downloading anything. But when I execute the command with remote-cache repository, it succeeds with the file downloaded. 

Kindly check and help me if it is a bug or an expected behavior.

Thanks!

**Comment by eyalbe4** [comment]
@asaddamhussain,
Hopefully you're using JFrog CLI and not this project, which has been deprecated a long time ago..
We can continue this discussion on https://github.com/JFrog/jfrog-cli-go
I'm therefore closing this issue.

**Comment by asaddamhussain** [comment]
@eyalbe4 
yes i am using jfrom cli, i will raise a issue there. 

Thanks
