### ISSUE TITLE
Bintray integration going to wrong folder?

### ISSUE THREAD

**Issue by dragon788** [JFrogDev/artifactory-cli-go#3]
I attempted to access 1.1.0 on Bintray and there isn't an executable available for download. After a bunch of clicking around I found in the Files tab that it had ended up in a subfolder and wasn't "visible" to the Bintray frontend.

**Comment by eyalbe4** [comment]
@dragon788, Could it be a wrong Bintray link you were using? 
We've just tried downloading one of the "art" executables and managed to do so. We navigated to [this link](https://bintray.com/jfrog/artifactory-cli-go/artifactory-cli-linux-amd64/1.1.0/view#files) through the Bintray Ui and then just clicked on the "art" file link which started the download (this is the linux-amd64 one).

**Comment by eyalbe4** [comment]
@dragon788, I think I understand the issue you described. We've just added the 1.1.0 executables to the main [jfrog / artifactory-cli-go](https://bintray.com/jfrog/artifactory-cli-go) Bintray page.
Enjoy using the client :)

**Comment by dragon788** [comment]
It appears the code publishing to the "Downloads" folder has regressed in 1.2.0 and higher. I would expect to see the art(.exe) file under Downloads rather than having to click Files and then click the file myself, as I was showing a coworker where to find the executable they were also confused by the number of clicks and the fact that it was so difficult to find.

https://bintray.com/jfrog/artifactory-cli-go/artifactory-cli-linux-amd64/1.0.1/view

vs.

https://bintray.com/jfrog/artifactory-cli-go/artifactory-cli-linux-amd64/1.2.0/view

**Comment by eyalbe4** [comment]
Got it @dragon788 .
We'll fix this soon and make sure the direct download is available for all (including future) versions.

**Comment by eyalbe4** [comment]
Issue fixed. Thanks @dragon788 .
