### ISSUE TITLE
Tool returns 0 on failure, should return a non-zero code

### ISSUE THREAD

**Issue by ghost** [JFrogDev/artifactory-cli-go#5]
Hi
Thanks for this Artifactory CLI, it's really useful!

However, I find that when I get an error, the CLI returns exit code 0. This is wrong, because when running it from a shell script or build tool, the operation will appear to have succeeded, even though it didn't.

Specific error was:

```
[Thread 0] Artifactory response: 404 Not Found
Uploaded 0 artifacts to Artifactory.
Failed uploading 1 artifacts to Artifactory.
$ echo $?
0
```

**Comment by eyalbe4** [comment]
Thanks for this feedback @ssssam !
We will handle this soon.

**Comment by eyalbe4** [comment]
Version 1.2.0 was released and includes this fix.
